version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MODE: dev
    networks:
      - app
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  mongo:
    image: mongo:5.0.4
    container_name: mongo
    restart: always
    networks:
      - app
    expose:
      - 27017
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_admin
    restart: always
    networks:
      - app
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - '8081:8081'

networks:
  app:
